version: 2
updates:
  - directory: "/"
    open-pull-requests-limit: 0
    package-ecosystem: "npm"
    rebase-strategy: auto
    schedule:
      interval: "daily"
      timezone: "America/Vancouver"
      time: "00:00"
    labels: 
      - "security"
      - "react"